# Generated by Django 5.2 on 2025-06-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0003_athleteinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='goals',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='athleteinfo',
            name='weight',
            field=models.TextField(default=''),
        ),
    ]
