# Generated by Django 5.2 on 2025-06-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0006_remove_athleteinfo_id_alter_athleteinfo_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='weight',
            field=models.TextField(blank=True, null=True),
        ),
    ]
