# Generated by Django 5.2 on 2025-06-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0007_alter_athleteinfo_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='goals',
            field=models.TextField(blank=True, default='Нет цели', null=True),
        ),
        migrations.AlterField(
            model_name='athleteinfo',
            name='weight',
            field=models.TextField(blank=True, default='50', null=True),
        ),
    ]
