# Generated by Django 5.2 on 2025-06-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0014_position_timestamp_run_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='timestamp',
        ),
    ]
