# Generated by Django 5.2 on 2025-06-28 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0016_collectibleitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectibleitem',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='collectible_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
